### ISSUE TITLE
Yaml files for deploying sample are out of date

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#1]
The yaml files under `config/samples/` are out of date, they're not aligned with the latest harbor CR spec.

kcustomization.yaml

```yaml
resources:
  - containerregistry_v1alpha1_harbor.yaml # wrong name
  - certificate.yaml
  - requirements.tmpl
```

goharbor_v1alpha_harbor.yaml

```yaml
# ...
registryCtl: # wrong
      image: "goharbor/harbor-registryctl:v1.10.0"
    registry:
      storageSecret: registry-storage
      cacheSecret: registry-cache
      image: goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.0
# ...

notary:
      publicURL: 'https://{{ env.Getenv "NOTARY_DOMAIN" }}'
      notaryDBMigratorImage: jmonsinjon/notary-db-migrator:v0.6.1 # wrong
      server:
        databaseSecret: notary-server-database
        image: goharbor/notary-server-photon:v0.6.1-v1.10.0
      signer:
        databaseSecret: notary-signer-database
        image: goharbor/notary-signer-photon:v0.6.1-v1.10.0
# ...
```
