### ISSUE TITLE
Unable to config OIDC login using day-2 HarborConfiguration CR

### ISSUE THREAD

**Issue by Simonkz** [goharbor/harbor-operator#1070]
harbor operator: v1.3.0
harbor: 2.5.1

Hi team, I'm trying to config OIDC login with day-2 config CR `HarborConfiguration`. 
After I applied my HarborConfiguration CR, I got 401 unauthorized error in exchange token step.

However, if I set the same settings in harbor Configuration UI page, I can login using OIDC without any issue. 

my config example:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-oidc
  namespace: cluster-sample-ns
type: Opaque
data:
  oidc_client_secret: my-client-secret     # tried to use base64(my-client-secret), not working
---
apiVersion: goharbor.io/v1beta1
kind: HarborConfiguration
metadata:
  name: oidc-config
  namespace: cluster-sample-ns
spec:
  configuration:
    authMode: oidc_auth
    oidcClientId: my-oidc-client-id
    oidcClientSecret: secret-oidc
    oidcEndpoint: https://my-idp.com/oidc
    oidcName: harbor-test
    oidcScope: openid
    oidcVerifyCert: false
  harborClusterRef: harborcluster-sample
```

```
>  kc -n cluster-sample-ns get harborconfiguration        
NAME          HARBORCLUSTER          STATUS    AGE
oidc-config   harborcluster-sample   Success   42s
```

error log in harbor-core pod
```
2023-08-28T09:42:21Z [ERROR] [/core/controllers/oidc.go:93]: Failed to exchange token, error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client"}
```

error in UI
```
GET https://<<ip>>.nip.io/c/oidc/callback?code=xxxxxxxxx&state=xxxxxxxxx
400  {"errors":[{"code":"BAD_REQUEST","message":"oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_client\"}"}]}
```

One more thing I found: 
If I applied my HarborConfiguration first and then copy/paste/save `my-client-secret` in UI, the OIDC login works without any issue.
