### ISSUE TITLE
The ready condition is False, but the core component is healthy

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#112]
# Pod Status
```
root@example-large0:~# kubectl get pod
NAME                                                      READY   STATUS    RESTARTS   AGE
all-in-one-database-postgresql-0                          1/1     Running   0          13h
all-in-one-minio-56d65664f8-znx6b                         1/1     Running   0          13h
all-in-one-redis-master-0                                 1/1     Running   0          13h
all-in-one-redis-slave-0                                  1/1     Running   0          13h
all-in-one-redis-slave-1                                  1/1     Running   0          13h
harborcluster-sample-harbor-core-669d75dd4-qh8fs          1/1     Running   0          2m3s
harborcluster-sample-harbor-jobservice-564cffbcb5-95dc9   1/1     Running   0          2m3s
harborcluster-sample-harbor-portal-bdd9d9b85-gjzjs        1/1     Running   0          2m3s
harborcluster-sample-harbor-registry-9f9f6b546-j7mf9      2/2     Running   0          2m3s
```

# Core Component Health

```
kubectl exec -it harborcluster-sample-harbor-core-669d75dd4-qh8fs bash

curl localhost:8080/api/health

{"status":"healthy","components":[{"name":"redis","status":"healthy"},{"name":"registry","status":"healthy"},{"name":"jobservice","status":"healthy"},{"name":"core","status":"healthy"},{"name":"registryctl","status":"healthy"},{"name":"portal","status":"healthy"},{"name":"database","status":"healthy"}]}
```

# Harbor Status
```
status:
  conditions:
  - lastTransitionTime: "2020-09-15T03:27:24Z"
    lastUpdateTime: "2020-09-15T03:27:24Z"
    status: "True"
    type: Applied
  - lastTransitionTime: "2020-09-15T11:09:17Z"
    lastUpdateTime: "2020-09-15T21:09:17Z"
    message: 'cannot get health response: unknown (get service harborcluster-sample-harbor-core)'
    reason: unknown (get service harborcluster-sample-harbor-core)
    status: "False"
    type: Ready
  observedGeneration: 1
```
