### ISSUE TITLE
Failed to deploy sample with `make sample`

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#2]
Error:

>Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "mharbor.kb.io": the server could not find the requested resource
Makefile:117: recipe for target 'sample' failed
make: *** [sample] Error 1

Check endpoints of webhook SVC:

```yaml
kubectl describe service -n harbor-operator-system harbor-operator-webhook-service
Name:              harbor-operator-webhook-service
Namespace:         harbor-operator-system
Labels:            <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"harbor-operator-webhook-service","namespace":"harbor-operator-sys...
Selector:          control-plane=controller-manager
Type:              ClusterIP
IP:                10.96.115.134
Port:              <unset>  443/TCP
TargetPort:        9443/TCP
Endpoints:         10.244.1.12:9443
Session Affinity:  None
Events:            <none>
```
