### ISSUE TITLE
redis service selector does not match the redis pod labels

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#255]
service selector:

```yaml
selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: harborcluster-sample
    app.kubernetes.io/part-of: redis-failover
```

pod labels:

```yaml
Labels:       app.kubernetes.io/component=redis
              app.kubernetes.io/instance=cluster-sample-ns
              app.kubernetes.io/managed-by=redis-operator
              app.kubernetes.io/name=harborcluster-sample-redis
              app.kubernetes.io/part-of=redis-failover
              controller-revision-hash=rfr-harborcluster-sample-redis-75d8c459f4
              goharbor.io/harbor-cluster=harborcluster-sample
              redisfailovers.databases.spotahome.com/name=harborcluster-sample-redis
              statefulset.kubernetes.io/pod-name=rfr-harborcluster-sample-redis-0
```
