### ISSUE TITLE
failed to initialize database core

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#308]
[ORM]2020/12/09 08:48:20 register db Ping `default`, pq: database "core" does not exist
2020-12-09T08:48:20Z [FATAL] [/core/main.go:120]: failed to initialize database: register db Ping `default`, pq: database "core" does not exist

![image](https://user-images.githubusercontent.com/188115/101607623-c22cd200-3a3f-11eb-9dcf-12dbcfc09915.png)

**Comment by steven-zou** [comment]
.PHONY: postgresql
postgresql: helm sample-database
	$(HELM) repo add bitnami https://charts.bitnami.com/bitnami
	$(HELM) upgrade --install harbor-database bitnami/postgresql \
		--set-string initdbScriptsConfigMap=harbor-init-db \
		--set-string existingSecret=harbor-database-password

**Comment by steven-zou** [comment]
`--set-string initdbScriptsConfigMap=harbor-init-db`

**Comment by steven-zou** [comment]
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: harbor-init-db
  files:
  - init-db.sql

secretGenerator:
- name: harbor-database-password
  literals:
  - postgresql-password=the-database-password
```
