### ISSUE TITLE
can't not external storage, controller will panic

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#312]
when setup external storage in full_stack.yaml like
```
  imageChartStorage:
    filesystem:
      registryPersistentVolume:
        claimName: sample-harbor-registry
```
operator controller will panic directly
![image](https://user-images.githubusercontent.com/188115/101649099-7a28a200-3a75-11eb-98e9-27f90b563e04.png)
