### ISSUE TITLE
Harbor CR status does not update when harborcore and registry is crash 

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#323]
The HarborCR
```
  status:
    conditions:
    - status: "False"
      type: InProgress
    - status: "False"
      type: Failed
    observedGeneration: 2
    operator:
      controllerName: harbor
      controllerVersion: dev
```
The POD
```
cluster-sample-ns    harborcluster-sample-harbor-harbor-core-5566648cd6-qgk6x          0/1     CrashLoopBackOff   68         5h27m
cluster-sample-ns    harborcluster-sample-harbor-harbor-core-77c994db59-ccbcw          0/1     CrashLoopBackOff   68         5h27m
cluster-sample-ns    harborcluster-sample-harbor-harbor-jobservice-558b8766f9-2fvkm    0/1     CrashLoopBackOff   68         5h27m
cluster-sample-ns    harborcluster-sample-harbor-harbor-portal-5d68dccb59-klcjs        1/1     Running            0          5h27m
cluster-sample-ns    harborcluster-sample-harbor-harbor-registry-5d6c9659c8-7p5k2      0/1     CrashLoopBackOff   91         5h27m
cluster-sample-ns    harborcluster-sample-harbor-harbor-registryctl-7c4fd5944b-6b9gp   1/1     Running            0          5h27m
```

It cause HarborCluster always show health
