### ISSUE TITLE
The storage class setting for redis and postgres doesn't work

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-operator#330]
Create Harbor with the following CR spec:
```
...
# Full stack Harbor
apiVersion: goharbor.io/v1alpha2
kind: HarborCluster
metadata:
  name: harborcluster-sample
  namespace: harbor
spec:
  ...
  inClusterDatabase:
    kind: PostgresSQL
    postgresSqlSpec:
      storage: 1Gi
      replicas: 2
      version: "12"
      storageClassName: wcpglobal-storage-profile
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
  inClusterStorage:
    kind: MinIO
    minIOSpec:
      replicas: 2
      volumesPerServer: 2
      version: RELEASE.2020-08-13T02-39-50Z
      volumeClaimTemplate:
        spec:
          storageClassName: wcpglobal-storage-profile
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 1000m
  inClusterCache:
    kind: Redis
    redisSpec:
      schema: redis
      server:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        storageClassName: wcpglobal-storage-profile
```
