### ISSUE TITLE
Remove annotation ”cert-manager.io/inject-ca-from: harbor-operator-ns/serving-cert“ from CRDs

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-operator#336]
The CRDs contain several annotation `cert-manager.io/inject-ca-from: harbor-operator-ns/serving-cert` which is useless and should be removed:
https://github.com/goharbor/harbor-operator/blob/develop/manifests/cluster/deployment.yaml#L3243

**Comment by steven-zou** [comment]
From the comment of the patch yaml that generates that annotation, this annotation is required.

```yaml
# The following patch adds a directive for certmanager to inject CA into the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: harbors.goharbor.io
```

This is not a bug we need to fix.

cc @ywk253100
