### ISSUE TITLE
Minio ingress spec rules backend svc name is not correct.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#338]
What can we help you?

The generated ingress spec:
```yaml
spec:
  rules:
  - host: minio.core.harbor.domain
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 9000
        path: /
        pathType: ImplementationSpecific
```

but existed svc name is minio-harborcluster-sample.

![image](https://user-images.githubusercontent.com/31262637/102226106-f3673f80-3f22-11eb-9dd8-3351a78c2f66.png)
