### ISSUE TITLE
Support image customization in the CRD spec

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#352]
two options：

- add registry prefix
- add image property together with pullpolicy and pullsecrets

**Comment by steven-zou** [comment]
offline discussed with @heww:

1st priority: load image from the `component.image`
2nd priority: load from the global repository settings:
```yaml
image_source:
  repository: https://goharbor.io
  tag: v2.1.2-customize_tag
  pullPolicy: IfNotPresent
  imagePullSecret: <secret>
```
3rd priority: load image by `configStore`(if it's set)
4th priority: load from hardcoded image
```go
consts (
  defaultPrefix = "goharbor/"
  defaultTag = "V2.1.2"
)
```
