### ISSUE TITLE
Support default network policy to enhance the security of deployed Harbor instance

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#398]
Add policy creation work in the component reconcile ctrl

**Comment by holyhope** [comment]
Operator should manage network policy for each harbor CR.
This would allow/deny connections between pods.

Proposal for a basic policies:

- ```
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: harbor-network-policy
    namespace: {{ .Namespace | quote }}
  spec:
    podSelector:
      matchLabels:
        component: core
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-controller
  ```
- ```
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: harbor-network-policy
    namespace: {{ .Namespace | quote }}
  spec:
    podSelector:
      matchLabels:
        component: portal
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-controller
  ```
