### ISSUE TITLE
Enhance the Harbor CRD

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#43]
Expose more configuration options:

```yaml
# log configurations
log:
  level: debug
  
# set proxy
proxy:
  http_proxy: 10.10.20.2
  https_proxy: 10.10.20.2
  no_proxy: 10.123.111.10
    components:
    - core
    - jobservice
    - clair

```

Use harbor version and a unified registry to define the images of Harbor components:

```yaml
# source registry of images
imageSource:
  registry: harbor.com
  imagePullSecrets:
   - pSecret
```
