### ISSUE TITLE
Harbor can not be created when enable minio redirect.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#433]
What can we help you?

## full_stack.yaml

```yaml
# Sample namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-sample-ns
---
# A secret of harbor admin password.
apiVersion: v1
kind: Secret
metadata:
  name: admin-core-secret
  namespace: cluster-sample-ns
data:
  secret: SGFyYm9yMTIzNDU=
type: Opaque
---
# Cert issuer
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cluster-sample-ns
spec:
  selfSigned: {}
---
# Certificates of ingress
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sample-public-certificate
  namespace: cluster-sample-ns
spec:
  secretName: sample-public-certificate
  dnsNames:
    - core.harbor.domain.172.18.0.2.xip.io
    - notary.harbor.domain.172.18.0.2.xip.io
    - minio.core.harbor.domain.172.18.0.2.xip.io
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
# Full stack Harbor
apiVersion: goharbor.io/v1alpha2
kind: HarborCluster
metadata:
  name: harborcluster-sample
  namespace: cluster-sample-ns
spec:
  imageSource:
    repository: quay.io/goharbor
  harborAdminPasswordRef: admin-core-secret
  externalURL: https://core.harbor.domain.172.18.0.2.xip.io
  expose:
    core:
      ingress:
        host: core.harbor.domain.172.18.0.2.xip.io
      tls:
        certificateRef: sample-public-certificate
  encryptionKeyRef: core-database-encryption
  internalTLS:
    enabled: true
  portal: {}
  registry: {}
  trivy:
    storage: {}
  core:
    tokenIssuer:
      name: selfsigned-issuer
      kind: Issuer
  inClusterDatabase:
    kind: PostgresSQL
    postgresSqlSpec:
      storage: 1Gi
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 10m
          memory: 25Mi
  inClusterStorage:
    kind: MinIO
    minIOSpec:
      redirect:
        enable: true
        expose:
          tls:
            certificateRef: sample-public-certificate
          ingress:
            host: minio.core.harbor.domain.172.18.0.2.xip.io
      replicas: 2
      volumesPerServer: 2
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      resources:
        requests:
          memory: 10Mi
          cpu: 50m
        limits:
          memory: 1000Mi
          cpu: 1000m
  inClusterCache:
    kind: Redis
    redisSpec:
      server:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 25Mi
      sentinel:
        replicas: 1
```

## harbor cluster status

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-02-03T09:40:56Z"
    message: harbor component database secrets are already create.
    reason: database already ready
    status: "True"
    type: DatabaseReady
  - lastTransitionTime: "2021-02-03T09:41:50Z"
    message: harbor component redis secrets are already create.
    reason: redis already ready
    status: "True"
    type: CacheReady
  - lastTransitionTime: "2021-02-03T09:41:49Z"
    message: 400 Bad Request
    reason: Create default bucket in minIO Error
    status: "False"
    type: StorageReady
  revision: 1612345310426556500
  status: unknown
```

## harbor operator error logs

```bash
2021-02-03T09:41:50.553Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "goharbor.io", "reconcilerKind": "HarborCluster", "controller": "harborcluster", "name": "harborcluster-sample", "namespace": "cluster-sample-ns", "error": "reconcile dependent services error: gos.Group error: 400 Bad Request"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/chlins/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/Users/chlins/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/Users/chlins/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/Users/chlins/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/chlins/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/chlins/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:90
```

## minio pod error logs
```bash
API: SYSTEM()
Time: 09:41:27 UTC 02/03/2021
Error: http: TLS handshake error from 10.244.0.78:57544: remote error: tls: bad certificate
       1: cmd/server-main.go:469:cmd.serverMain.func2()
Unable to read 'format.json' from https://minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local:9000/export0: Post "https://minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local:9000/minio/storage/export0/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate is valid for core.harbor.domain.172.18.0.2.xip.io, notary.harbor.domain.172.18.0.2.xip.io, minio.core.harbor.domain.172.18.0.2.xip.io, not minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local

Unable to read 'format.json' from https://minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local:9000/export1: Post "https://minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local:9000/minio/storage/export1/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate is valid for core.harbor.domain.172.18.0.2.xip.io, notary.harbor.domain.172.18.0.2.xip.io, minio.core.harbor.domain.172.18.0.2.xip.io, not minio-harborcluster-sample-zone-harbor-1.minio-harborcluster-sample-hl.cluster-sample-ns.svc.cluster.local

Waiting for a minimum of 2 disks to come online (elapsed 1m31s)


API: SYSTEM()
Time: 09:41:27 UTC 02/03/2021
Error: http: TLS handshake error from 10.244.0.78:57558: remote error: tls: bad certificate
       1: cmd/server-main.go:469:cmd.serverMain.func2()

API: SYSTEM()
Time: 09:41:27 UTC 02/03/2021
Error: http: TLS handshake error from 10.244.0.78:57560: remote error: tls: bad certificate
       1: cmd/server-main.go:469:cmd.serverMain.func2()

API: SYSTEM()
Time: 09:41:28 UTC 02/03/2021
Error: http: TLS handshake error from 10.244.0.78:57568: remote error: tls: bad certificate
```
