### ISSUE TITLE
Restriction for one Harbor Cluster CR per namespace at maximum

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#523]
Namespace is usually used as a boundary for tenants.  
We should provide flag for admin to restrict the 1:1 mapping between Harbor instance and namespace.

**Comment by holyhope** [comment]
Hello @reasonerjt 

IMO This should be done with [`ResourceQuota`](https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota).
With that feature, you will be able to restrict the amount of `HarborCluster`.

It seems easier that the cluster administrator manages the quota on his side with a built-in feature.

WDYT?

**Comment by steven-zou** [comment]
> his side with a built-in feature.

@reasonerjt @ywk253100 

Could you guys check if the solution mentioned by @holyhope can fill the gap you raised?

**Comment by bitsf** [comment]
@heww will verify this ResourceQuota feature

**Comment by bitsf** [comment]
what behavior if there are already two harbor

**Comment by heww** [comment]
ResourceQuota is ok to limit the count of the harbor cluster. 

Here is the ResourceQuota I used to do the test.
```yaml
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: harborcluster-counts
  namespace: cluster-sample-ns
spec:
  hard:
    count/harborclusters.goharbor.io: "1"
```
