### ISSUE TITLE
Remove minio console deployment

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#573]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    goharbor.io/deploy-engine: Kustomization
    goharbor.io/deploy-mode: cluster
    goharbor.io/operator-version: v1.0.0
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: console
  namespace: harbor-operator-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      annotations:
        goharbor.io/deploy-engine: Kustomization
        goharbor.io/deploy-mode: cluster
        goharbor.io/operator-version: v1.0.0
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      labels:
        app: console
    spec:
      containers:
      - args:
        - server
        env:
        - name: CONSOLE_OPERATOR_MODE
          value: "on"
        image: minio/console:v0.6.3
        imagePullPolicy: IfNotPresent
        name: console
        ports:
        - containerPort: 9090
          name: console-http
        - containerPort: 9443
          name: console-https
      serviceAccountName: console-sa
```
