### ISSUE TITLE
Miss Issure for registry cert

### ISSUE THREAD

**Issue by Ghostbaby** [goharbor/harbor-operator#60]
Miss create `Issuer` for registry cert in Harbor CR namespace.

![image](https://user-images.githubusercontent.com/3281480/87378759-221e6a00-c5c1-11ea-8d0a-004347d7e2a2.png)

Need to use YAML to create `Issuer`.
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: pg
spec:
  selfSigned: {}
```
