### ISSUE TITLE
Install Harbor with external redis without password failed

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor-operator#608]
Install Harbor with https://github.com/goharbor/harbor-operator/blob/master/manifests/samples/harborcluster_standard_stack_external.yaml
Failed to login to the harbor and Harbor operator log dump some error message with missing secert of redis.

**Comment by steven-zou** [comment]
@stonezdj 

Have you created the secret to include the Redis password and update it into the spec?

```yaml
 redis:
    host: harbor-redis-master
    passwordRef: harbor-redis  # here
    port: 6379
```
