### ISSUE TITLE
Refine the database spec in HarborCluster CRD to provide more clear and flexible db configurations

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#643]
CRD version -> v1beta1

```yaml
database:
  kind: postgresql
  spec:
    # PostgreSQL user name to connect as.
    # Defaults to be the same as the operating system name of the user running the application.
    username: postsql # Required
    # Secret containing the password to be used if the server demands password authentication.
    passwordRef: psqlSecret # Optional
    # PostgreSQL hosts.
    # At least 1.
    hosts:
      # Name of host to connect to.
      # If a host name begins with a slash, it specifies Unix-domain communication rather than
      # TCP/IP communication; the value is the name of the directory in which the socket file is stored.
      - host: psql # Required
      # Port number to connect to at the server host,
      # or socket file name extension for Unix-domain connections.
      # Zero, specifies the default port number established when PostgreSQL was built.
        port: 5432 # Optional
    # PostgreSQL has native support for using SSL connections to encrypt client/server communications for increased security.
    # Supports values ["disable","allow","prefer","require","verify-ca","verify-full"].
    sslMode: prefer # Optional, default=prefer
    prefix: prefix # Optional
```

or handle in-cluster db powered by zlando/postgresql

```yaml
database:
  kind: zlando/postgresql
  spec:
    operatorVersion: 1.5.0
    # Image name for the PostgresSQL. It will override the default one.
      image: my-psql # Optional
      # Image pull policy. It will override the global 'imageSource' settings and the default one.
      imagePullPolicy: # Optional, default = IfNotPresent
      # Image pull secrets. It will override the global 'imageSource' settings if it has been set.
      imagePullSecrets:
        - name: myHarborRegSecretOfPsql
      # Specify the storage size for the PostgresSQL.
      storage: 1Gi # Optional, default="1Gi"
      # Replicas of PostgresSQL instances.
      replicas: 3 # Optional, default=3
      # The storage class used for creating storage.
      storageClassName: default # Optional
      # If provided, use these requests and limit for cpu/memory resource allocation
      # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
      resources: # Optional
        # Limits describes the maximum amount of compute resources allowed.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
        limits: {} # Optional
        # Requests describes the minimum amount of compute resources required.
        # If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
        # otherwise to an implementation-defined value.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
        requests: {} # Optional
```
