### ISSUE TITLE
Refine the redis spec in HarborCluster CRD to provide more clear and flexible configurations

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#644]
CRD version: v1beta1?

```yaml
redis:
  kind: redis
  spec:
    # Server host.
    host: myredis.com # Required
    # Server port.
    port: 6347 # Required
    # For setting sentinel masterSet.
    sentinelMasterSet: sentinel # Optional
    # Secret containing the password to use when connecting to the server.
    passwordRef: pwdSecret # Optional
    # Secret containing the client certificate to authenticate with.
    certificateRef: cert # Optional
```

Or for the in-cluster redis powered by RedisFailover,

```yaml
redis:
  kind: redisfailover
  spec:
      operatorVersion: 1.0
    # Image name for the Redis. It will override the default one.
      image: my-redis # Optional
      # Image pull policy. It will override the global 'imageSource' settings and the default one.
      imagePullPolicy: # Optional, default = IfNotPresent
      # Image pull secrets. It will override the global 'imageSource' settings if it has been set.
      imagePullSecrets:
        - name: myHarborRegSecretOfRedis
      # Redis sentinel
      sentinel: # Required
        # Replicas of the sentinel service.
        replicas: 3 # Optional, default=3
      # Redis server.
      server: # Required
        # Replicas of the server.
        replicas: 3 # Optional, default=3
        # Storage class used to apply storage of redis.
        StorageClassName: default # Optional
        # Storage size.
        storage: 1Gi # Optional
        # If provided, use these requests and limit for cpu/memory resource allocation
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
        resources: # Optional
          # Limits describes the maximum amount of compute resources allowed.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          limits: {} # Optional
          # Requests describes the minimum amount of compute resources required.
          # If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
          # otherwise to an implementation-defined value.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
          requests: {} # Optional
```
