### ISSUE TITLE
ingress and loadbalancer choice problem

### ISSUE THREAD

**Issue by cndoit18** [goharbor/harbor-operator#716]
There are some problems in selecting ingress and loadbalancer. I can't select both, and some must have ingress
![image](https://user-images.githubusercontent.com/55286565/126746973-408641ed-ba68-41f7-8eaa-ceac1b51d9ec.png)

**Comment by bitsf** [comment]
please attach the yaml how to reproduce this

**Comment by bitsf** [comment]
we should check this in harborcluster controller webhook

**Comment by cndoit18** [comment]
testcase:
```
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harborcluster-sample
  namespace: cluster-sample-ns
spec:
  version: 2.3.0
  logLevel: info
  imageSource:
    repository: ghcr.io/goharbor
  harborAdminPasswordRef: admin-core-secret
  externalURL: https://core.harbor.domain
  expose:
    core:
      loadbalancer:
        enable: true
      tls:
        certificateRef: sample-public-certificate
    notary:
      ingress:
        host: notary.harbor.domain
        controller: default
      loadbalancer:
        enable: true
      tls:
        certificateRef: sample-public-certificate
    portal:
      ingress:
        host: portal.harbor.domain
        controller: default
      tls:
        certificateRef: sample-public-certificate
  internalTLS:
    enabled: true
  portal: {}
  registry:
    metrics:
      enabled: true
  core:
    tokenIssuer:
      name: selfsigned-issuer
      kind: Issuer
    metrics:
      enabled: true
  chartmuseum: {}
  exporter: {}
  trivy:
    skipUpdate: false
    storage: {}
  notary:
    migrationEnabled: true
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        storage: 1Gi
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
  storage:
    kind: MinIO
    spec:
      minIO:
        operatorVersion: "4.0.6"
        replicas: 2
        secretRef: minio-access-secret
        redirect:
          enable: true
          expose:
            ingress:
              host: minio.harbor.domain
            tls:
              certificateRef: sample-public-certificate
        volumesPerServer: 2
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  cache:
    kind: RedisFailover
    spec:
      redisFailover:
        operatorVersion: "1.0.0"
        server:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
        sentinel:
          replicas: 1

```
