### ISSUE TITLE
failed to enable loadbalancer

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#755]
version: v1.1.0
steps:
1. install kind k8s cluster
2. install metallb
https://metallb.universe.tf/installation/
helm repo add metallb https://metallb.github.io/metallb
helm install metallb metallb/metallb -f values.yaml
```
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 198.51.100.0/24
```

3. install harbor-operator v1.1.0
4. install sample harbor minimal_stack_fs.yaml 
```
   expose:
     core:
-      ingress:
-        host: core.harbor.domain
-        controller: default
+      loadbalancer:
+        enable: true
       tls:
         certificateRef: sample-public-certificate
   internalTLS:
```

5. failed to curl loadbalancer ip
