### ISSUE TITLE
Unable to apply Day2 configs to configure OIDC

### ISSUE THREAD

**Issue by divyanshuch1** [goharbor/harbor-operator#769]
I am unable to apply day2 configs to apply the OIDC configuration to running harbor cluster.
Changing Auth mode and OIDC setting through UI of portal working fine but facing challenge in doing the same with `kind=harborconfiguration` 

I am applying the following manifest
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
  namespace: cluster-sample-ns
type: Opaque
stringData:
  # the key is same with fields name.
  oidc_client_secret: 76e6fa8d-4835
  
  
  
apiVersion: goharbor.io/v1beta1
kind: HarborConfiguration
metadata:
  name: test-config
  namespace: cluster-sample-ns
spec:
  # your harbor configuration
  configuration:
    auth_mode: oidc
    oidc_client_secret: secret-sample
    oidc_name: "keycloak"
    oidc_endpoint: "https://keycloak-keycloak.apps.op.divyanshutech.com/auth/realms/harbor"
    oidc_client_id: "harbor"
    oidc_client_secret: secret-sample
    oidc_groups_claim: "harbor"
    oidc_admin_group:
    oidc_scope: "openid,offline_access"
    oidc_verify_cert: false
    oidc_auto_onboard: false
  harborClusterRef: harborcluster-sample
  ```
  

![Screenshot from 2021-09-10 21-44-01](https://user-images.githubusercontent.com/83651093/132884813-6bd10ea6-c854-4028-99a4-a71f5d330c81.png)
