### ISSUE TITLE
Minio doesn't seem to work on EKS

### ISSUE THREAD

**Issue by sagikazarmark** [goharbor/harbor-operator#771]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Trying to install Harbor using minio, but the minio tenant never comes up, it stucks in `Provisioning MinIO Headless Service` state.

**Steps to reproduce the problem:**
1. Create an EKS cluster
2. Install the operator enabling minio, postgres and redis operators

**Versions:**
Please specify the versions of following systems.

- harbor operator version:1.1.0
- harbor version: 2.3.2
- kubernetes version: 1.21
- Any additional relevant versions such as CertManager
  - cert-manager: 1.5.3

**Additional context:**

- **Harbor dependent services:**
```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harbor
spec:
  version: "${harbor_version}"
  logLevel: debug
  harborAdminPasswordRef: ${admin_secret}
  externalURL: https://${core_domain}
  expose:
    core:
      ingress:
        host: ${core_domain}
      tls:
        certificateRef: ${cert_secret}
    notary:
      ingress:
        host: notary.${base_domain}
      tls:
        certificateRef: ${cert_secret}
  internalTLS:
    enabled: true
  portal: {}
  registry:
    replicas: 1
    metrics:
      enabled: true
  core:
    replicas: 3
    tokenIssuer:
      name: ca
      kind: ClusterIssuer
    metrics:
      enabled: false
    log:
      level: debug
  chartmuseum: {}
  exporter: {}
  trivy:
    skipUpdate: false
    storage: {}
  notary:
    migrationEnabled: true
  database:
    kind: "Zlando/PostgreSQL"
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        storage: 20Gi
        replicas: 1
        resources:
          limits:
            cpu: 5000m
            memory: 2500Mi
          requests:
            cpu: 1000m
            memory: 2500Mi
  cache:
    kind: RedisFailover
    spec:
      redisFailover:
        operatorVersion: "1.0"
        sentinel:
          replicas: 1
        server:
          replicas: 1
  storage:
    kind: MinIO
    spec:
      minIO:
        operatorVersion: "4.0.6"
        redirect:
          enable: true
          expose:
            ingress:
              host: minio.${base_domain}
              tls:
                certificateRef: ${cert_secret}
        secretRef: ${minio_secret}
        replicas: 2
        volumesPerServer: 2
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi

```
- **Log files:** Collect logs and attach them here if have.
- **Kubernetes:** EKS cluster created on AWS

Several sources suggest that CSR is broken on EKS and that an earlier version of the operator (<4.1.0) might work fine. I haven't been able to test this theory, but the chart is currently locked to >4.1

- https://github.com/minio/operator/issues/743
- https://github.com/minio/operator/issues/796
