### ISSUE TITLE
Missing minio ingress annotations 

### ISSUE THREAD

**Issue by MartinSchmidt123** [goharbor/harbor-operator#793]
**Expected behavior and actual behavior:**
My kubernetes cluster has two ingress controllers and I want the harbor operator to use the non-default ingress controller for all components. In my case this means adding the following annotation to the ingress:
`kubernetes.io/ingress.class: nginx`
The CRD definition from https://github.com/goharbor/harbor-operator/blob/v1.1.1/docs/CRD/custom-resource-definition.md#minio allows for annations.

While the top-level expose will create annotations of the ingress for core and notary via

```
  expose:
    core:
      ingress:
        host: <core-host>
        controller: default
        annotations:
          kubernetes.io/ingress.class: nginx
      tls:
        certificateRef: <core-cert-ref>
    notary:
      ingress:
        host: <notary-host>
        controller: default
        annotations:
          kubernetes.io/ingress.class: nginx
      tls:
        certificateRef: <notary-cert-ref>
```

adding ingress annotations for minio via

 ```
 storage:
    kind: MinIO
    spec:
      minIO:
        operatorVersion: "4.0.6"
        replicas: 2
        secretRef: minio-access-secret
        redirect:
          enable: true
          expose:
            ingress:
              host: <minio-host>
              controller: default
              annotations:
                kubernetes.io/ingress.class: nginx
            tls:
              certificateRef: <minio-cert-ref>
```

will not add the annotations to the ingress.

**Steps to reproduce the problem:**

1. Setup a kubernetes cluster with two ingress controllers
2. Use https://github.com/goharbor/harbor-operator/blob/master/manifests/samples/full_stack.yaml and add a ingress annotation for minio as above
3. Notice that the annotation is not added to the ingress

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.1.1
- harbor version: 2.3.3
- kubernetes version: 1.21.3

**Additional context:**

- I am not sure but we might need to implement https://github.com/goharbor/harbor-operator/blob/v1.1.1/pkg/cluster/controllers/storage/tenant.go#L276
