### ISSUE TITLE
How to disable the redirect with an external S3 storage in HarborCluster Operator?

### ISSUE THREAD

**Issue by sun7927** [goharbor/harbor-operator#798]
When create a HarborCluster CR with an external S3 storage, is there any way to disable the redirect option?

```
==================

apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: cluster
spec:
  version: 2.3.3
  logLevel: debug
  ...
  storage:
    kind: S3
    spec:
      s3: # Optional
        accesskey: <key>
        secretkeyRef: harbor-cluster-deps-credentials # Optional
        regionendpoint: <endpoint> # Required
        bucket: <bucketname> # Required
        rootdirectory: registry # Optional
        storageclass: STANDARD # Optional, default="STANDARD"
        skipverify: true # Optional, default=false
        secure: false # Optional, default=true
        v4auth: true # Optional, default=true
        chunksize: 5242880 # Optional, minimal = 5242880
        multipartcopychunksize: 33554432
        multipartcopymaxconcurrency: 100
        multipartcopythresholdsize: 33554432

```

==================

The operator will generate the Harbor CR as:

```
apiVersion: goharbor.io/v1beta1
kind: Harbor
metadata:
  name: cluster-harbor
spec:
  imageChartStorage:
    redirect:
      disable: false
    s3:
    ...

```
 

Question: how to disable the redirect when using external S3 storage?
