### ISSUE TITLE
non numberic nonroot user `nonroot` cause deploy issue in strict K8s cluster

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#82]
`Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root`

Dockerfile use non numberic nonroot user nonroot
```shell
USER nonroot:nonroot
```
==>
```shell
USER 1000:1000
```

**Comment by steven-zou** [comment]
Similar case for miniO:

```yaml
containerStatuses:
  - image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    imageID: ""
    lastState: {}
    name: minio
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: container has runAsNonRoot and image will run as root
        reason: CreateContainerConfigError
```
