### ISSUE TITLE
Unnecessary backend in ingress when portal is disabled

### ISSUE THREAD

**Issue by heww** [goharbor/harbor-operator#823]
Install the harbor cluster without portal, but the ingress still has backend for the portal.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cluster-sample-ns.core.checksum.goharbor.io/harborcluster-sample-harbor-harbor: "6362"
    cluster-sample-ns.harbor.checksum.goharbor.io/harborcluster-sample-harbor: "3"
    cluster-sample-ns.portal.checksum.goharbor.io/harborcluster-sample-harbor-harbor: "5286"
    goharbor.io/warning: ⚠️ This Resource is managed by *harbor* ⚠️
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  labels:
    goharbor.io/operator-controller: harbor
    goharbor.io/operator-version: 0.0.0-dev
  name: harborcluster-sample-harbor-harbor
  namespace: cluster-sample-ns
spec:
  rules:
  - host: core.xxx.xxx.xxx.xxx.nip.io
    http:
      paths:
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-portal
            port:
              number: 443
        path: /
        pathType: Prefix
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-core
            port:
              number: 443
        path: /api/
        pathType: Prefix
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-core
            port:
              number: 443
        path: /service/
        pathType: Prefix
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-core
            port:
              number: 443
        path: /v2
        pathType: Prefix
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-core
            port:
              number: 443
        path: /chartrepo/
        pathType: Prefix
      - backend:
          service:
            name: harborcluster-sample-harbor-harbor-core
            port:
              number: 443
        path: /c/
        pathType: Prefix
  tls:
  - hosts:
    - core.xxx.xxx.xxx.xxx.nip.io
    secretName: sample-public-certificate
```
