### ISSUE TITLE
Clair updater is disabled by hardcoded interval settings (0s)

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#84]
Clair updater interval is hardcoded to 0s and then the updater is disabled.

```yaml
  updater:
    interval: 0s
    enabledupdaters:
```
