### ISSUE TITLE
sign off release 1.2.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#862]
please maintainers help test harbor-operator 1.2.0 rc build, and sign off here
- [x] Steven Zou , steven-zou , VMware
- [x] Ziming Zhang , bitsf , VMware
- [x] Weiwei He , heww, VMware
- [x] Canfeng Wang , wangcanfengxs , Netease
- [ ] Huijun Zhu , Ghostbaby , Yunmanman
- [x] Xiaoyang Zhu , soulseen , Shoppee
- [x] Chengyu Zhang , chlins , VMware
- [x] Xiongxiong Yuan, yxxhero, Qunar:

* helm install
* docker pull
* docker push
* docker login  
* api is ok  

- [ ] Yinan Li , cndoit18 , Qihu360

**Comment by steven-zou** [comment]
# Sign off v1.2:

## Steps:**

Install harbor-operator v1.2 by `kubectl apply -f "k8s apply -f "https://raw.githubusercontent.com/goharbor/harbor-operator/release-1.2.0/manifests/cluster/deployment.yaml""`

Deploy full-stack Harbor with the [manifest yaml ](https://github.com/goharbor/harbor-operator/blob/master/manifests/samples/full_stack.yaml)under `manifest/samples` (with core.<IP>.nip.io) on kind (k8s 1.22)

Login harbor,
Create project,
Add docker hub registry,
Create replication rule to pull nginx/haproxy latest images to the crated project
Scan images
Check versions
Check cluster pods

Update configurations via CRD:

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborConfiguration
metadata:
  name: test-config
  namespace: cluster-sample-ns
spec:
  # your harbor configuration
  configuration:
    robotTokenDuration: 45
    robotNamePrefix: harbor$
    notificationEnable: false
  harborClusterRef: harborcluster-sample
```

## Functions checked

- [x] - new k8s
- [x] - new storage driver
- [x] - bump harbor 2.4.1
- [x] - bump redis
- [x] - bump minio
- [x] - bump psql
- [x] - CRD based configuration
- [ ] - support ingress class
- [x] - support optional component removal
- [x] - put registry and registryctl pods in one
- [ ] - make portal component optional


## Issues found

- The day2 CRD doc is not correct - issue created and need to fix 
- The harbor operator version is not correct (should be `v1.2.0` but still `dev_master`)
