### ISSUE TITLE
Sample code given in the day2 configuration doc is not correct

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#867]
see https://github.com/goharbor/harbor-operator/blob/release-1.2.0/docs/day2/day2-configurations.md

More background: https://github.com/goharbor/harbor-operator/issues/862#issuecomment-1075031757

**Comment by steven-zou** [comment]
The sample code should be:

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborConfiguration
metadata:
  name: test-config
  namespace: cluster-sample-ns
spec:
  # your harbor configuration
  configuration:
    robotTokenDuration: 45
    robotNamePrefix: harbor$
    notificationEnable: false
  harborClusterRef: harborcluster-sample
```
