### ISSUE TITLE
Registry metrics cannot be scraped with default configuration

### ISSUE THREAD

**Issue by sagikazarmark** [goharbor/harbor-operator#875]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Prometheus should be able to scrape the metrics endpoint of the registry when it's enabled, but Prometheus is unable to connect the metrics endpoint.

**Steps to reproduce the problem:**
Create a new HarborCluster:

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harbor
spec:
  version: "2.3.2"
  registry:
    metrics:
      enabled: true
```

Try to scrape the metrics endpoint:

```shell
kubectl port-forward svc/harbor-harbor-harbor-registry 8001
```

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.1.1
- harbor version: 2.3.2
- kubernetes version: 1.21
- Any additional relevant versions such as CertManager

**Additional context:**

The problem is present in the latest version as well and is caused by a hardcoded port number [here](https://github.com/goharbor/harbor-operator/blob/master/controllers/goharbor/registry/deployments.go#L56).

While the default port number is 8001 everywhere, the podspec is hardcoded to 5001.

As a workaround, you can set the metrics port manually to 5001 everywhere else:

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harbor
spec:
  version: "2.3.2"
  registry:
    metrics:
      enabled: true
      port: 5001
```

However, with 1.1.1 version of the operator this wasn't enough. I had to manually edit the registry resource as well, because the operator didn't update it. Then I had to restart the registry deployment because the config change didn't trigger a rollout. This last one should probably handled as a separate issue.
