### ISSUE TITLE
Change the default namespace to harbor-operator

### ISSUE THREAD

**Issue by sagikazarmark** [goharbor/harbor-operator#881]
**Is your feature request related to a problem? Please describe.**
The current default namespace is `harbor-operator-ns` stutters.

**Describe the solution you'd like**
Change the default namespace to `harbor-operator`.

Alternatively, don't specify a namespace at all (don't even create it) and let the user decide the namespace to use (kustomize can still account for the replacements).

**Additional context**
This is technically a breaking change, but only in the deployment config which should mostly serve as reference anyway.

Here is the current workaround:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor-operator

resources:
  # Namespace is already created by the upstream manifest
  - https://raw.githubusercontent.com/goharbor/harbor-operator/v1.1.2/manifests/harbor/deployment.yaml

# Fix namespaced references in various resources
replacements:
  - source:
      group: apps
      version: v1
      kind: Deployment
      name: harbor-operator
      fieldPath: metadata.namespace
    targets:
      - select:
          group: cert-manager.io
          version: v1
          kind: Certificate
          name: serving-cert
        fieldPaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: .
          index: 1
      - select:
          group: admissionregistration.k8s.io
          version: v1
          kind: ValidatingWebhookConfiguration
          name: validating-webhook-configuration
        fieldPaths:
          - metadata.annotations.cert-manager\.io/inject-ca-from
        options:
          delimiter: /
          index: 0
      - select:
          group: admissionregistration.k8s.io
          version: v1
          kind: MutatingWebhookConfiguration
          name: mutating-webhook-configuration
        fieldPaths:
          - metadata.annotations.cert-manager\.io/inject-ca-from
        options:
          delimiter: /
          index: 0
      - select:
          group: apiextensions.k8s.io
          version: v1
          kind: CustomResourceDefinition
        fieldPaths:
          - metadata.annotations.cert-manager\.io/inject-ca-from
        options:
          delimiter: /
          index: 0

patchesJson6902:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |
      - op: replace
        path: /metadata/name
        value: harbor-operator
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |
      - op: replace
        path: /metadata/name
        value: harbor-operator
```
