### ISSUE TITLE
harbor-core-tokencert using wrong issuer

### ISSUE THREAD

**Issue by fawadasaurus** [goharbor/harbor-operator#923]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I was trying to create my cluster using the HarborCluster custom resource.  It was failing to complete because a certificate was still pending.  The certificate was {namespace}-harbor-harbor-core-tokencert.

**Steps to reproduce the problem:**
Use the example manifests to create a HarborCluster.

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.2.0
- harbor version: 2.4.2
- kubernetes version: 1.22.6
- Any additional relevant versions such as CertManager: whatever is included with harbor operator

**Additional context:**
Before, it was trying to use my acme issuer:
```
spec:
  commonName: registry-harbor-harbor-core-tokencert
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: registry-cert-issuer
  privateKey:
    algorithm: RSA
    size: 4096
  secretName: registry-harbor-harbor-core-tokencert
  usages:
    - signing
```

I fixed it by changing the issuer to the harbor-internal issuer and not my ACME issuer.
After:
```spec:
  dnsNames:
    - registry-harbor-harbor-core-tokencert
  duration: 2160h0m0s
  issuerRef:
    name: registry-harbor-harbor-internal
  privateKey:
    algorithm: RSA
    size: 4096
  secretName: registry-harbor-harbor-core-tokencert
  usages:
    - signing
```

- **Harbor dependent services:**
  - Context info of postgreSQL
  - Context info of Redis
  - Context info of storage
- **Log files:** Collect logs and attach them here if have.
- **Kubernetes:** How Kubernetes access was provided (what cloud provider, service-account configuration, ...).
