### ISSUE TITLE
database not auto-scale

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor-operator#935]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I initially set the `replicate=2` of the `database` and started two pods. After that, I modified `replicate=1` and found that there are still two pods.

**Steps to reproduce the problem:**
- set follow config
```yaml
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        image: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
        storage: 1Gi
        replicas: 2
```
- kubectl apply -f 
- wait success, change database.replicas=1
```yaml
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        image: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
        storage: 1Gi
        replicas: 1
```
- kubectl apply -f 
- watch database pod number

**Versions:**
Please specify the versions of following systems.

- harbor operator version: [ghcr.io/goharbor/harbor-operator:dev_master]
- harbor version: [no]
- kubernetes version: [1.24.0]
- Any additional relevant versions such as CertManager: cert-manager-controller:v1.9.1
