### ISSUE TITLE
harborclusters status is error

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor-operator#936]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: status=health
Actual behavior: status=unhealthy

**Steps to reproduce the problem:**

1. kubectl apply -f harborcluster.yaml
2. kubectl apply -f registry-pv.yaml
3. kubectl apply -f redis-pv.yaml
4. kubectl apply -f postgresql-pv.yaml
5. watch postgresql status is running
6. wait harborcluster status is unhealth

**Versions:**
Please specify the versions of following systems.

- harbor operator version: [harbor-operator:dev_master]
- harbor version: [no]
- kubernetes version: [1.24.0]
- Any additional relevant versions such as CertManager

- **Harbor dependent services:**
  - Context info of postgreSQL
```shell
[root@localhost ~]# kubectl get postgresqls.acid.zalan.do
NAME                                      TEAM                 VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
postgresql-default-harborcluster-sample   postgresql-default   12        1      1Gi      100m          250Mi            33m   Running
```
 
- harborclasster
```shell
[root@localhost ~]# kubectl get harborclusters.goharbor.io harborcluster-sample
NAME                   PUBLIC URL                   STATUS
harborcluster-sample   https://core.harbor.domain   unhealthy
```
$ `kubectl get harborclusters.goharbor.io harborcluster-sample -o yaml`
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-07-29T06:28:56Z"
    status: "True"
    type: StorageReady
  - lastTransitionTime: "2022-07-29T06:28:56Z"
    message: psql is Creating
    reason: Database is not ready
    status: "False"
    type: DatabaseReady
  - lastTransitionTime: "2022-07-29T06:28:56Z"
    message: harbor component redis secrets are already create.
    reason: redis already ready
    status: "True"
    type: CacheReady
  - message: New generation detected
    reason: newGeneration
    status: "True"
    type: InProgress
  observedGeneration: 2
  operator:
    controllerGitCommit: 8a09ac29ed1dfd0823639579d49da25152277d17
    controllerName: harborcluster
    controllerVersion: dev_master
  revision: 1659076136495871178
  status: unhealthy
```

database status is `running`, the `harborcluster` status is still `unhealthy` after waiting for more than 30 minutes
