### ISSUE TITLE
not use default ingress controller

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor-operator#944]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I created the ingress class and set it as the default ingress (`kubectl annotate ingressclasses nginx ingressclass.kubernetes.io/is-default-class=true`), when the ingress in the harborcluster does not set the ingressClassName, the rules cannot be created correctly in the ingress controller .

Hope that the ingress rules can be set correctly when `spec.export.core.ingress.controller=default`

**Steps to reproduce the problem:**
```yaml
expose:
    core:
      ingress:
        host: core.harbor.domain
        controller: default
```

kubectl apply -f 

**Versions:**
Please specify the versions of following systems.

- harbor operator version: [main]
- harbor version: [2.5.2]
- kubernetes version: [1.24.0]
- Any additional relevant versions such as CertManager
