### ISSUE TITLE
harbor.Spec.Core.TokenIssuer is not omitempty

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor-operator#945]
What can we help you?

1、I first declared a `harborclass` yaml，in this yaml `harbor.Spec.Core.TokenIssuer` is not set, then run `kubectl apply -f test.yaml`，i watch harbor-operator pod is print error log。

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harborcluster-sample
  namespace: test-harbor
  labels:
    app: harbor.cluster
spec:
  version: 2.5.0
  logLevel: debug
  imageSource:
    repository: ghcr.io/goharbor
  harborAdminPasswordRef: admin-core-secret
  externalURL: http://test.harbor
  expose:
    core:
      ingress:
        host: test.harbor
        controller: default
        ingressClassName: nginx
  internalTLS:
    enabled: false
  registry:
    replicas: 1
    metrics:
      enabled: true
  jobservice:
    replicas: 2
  portal:
    replicas: 2
  core:
    image: ghcr.io/goharbor/harbor-core:2.5.0
    replicas: 2
    metrics:
      enabled: true
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        image: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
        storage: 1Gi
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
  storage:
    kind: FileSystem
    spec:
      fileSystem:
        registryPersistentVolume:
          claimName: sample-harbor-registry
  cache:
    kind: RedisFailover
    spec:
      redisFailover:
        operatorVersion: "1.0.0"
        server:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
        sentinel:
          replicas: 1
```

2、harbor operator error log
```shell
1.6601110352941918e+09	ERROR	controller.harbor	Reconciler error	{"reconciler group": "goharbor.io", "reconciler kind": "Harbor", "name": "harborcluster-sample-harbor", "namespace": "test-harbor", "error": "cannot set status to error: cannot set conditions to error: apply cert-manager.io/v1, Kind=Certificate (test-harbor/harborcluster-sample-harbor-harbor-core-tokencert): apply: admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified: apply cert-manager.io/v1, Kind=Certificate (test-harbor/harborcluster-sample-harbor-harbor-core-tokencert): apply: admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified", "errorVerbose": "admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified\napply\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).applyAndCheck\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/controller/common.go:174\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).ProcessFunc.func1\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/controller/resource.go:148\ngithub.com/goharbor/harbor-operator/pkg/graph.(*resourceManager).Run.func1\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/graph/runner.go:42\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_amd64.s:1571\napply cert-manager.io/v1, Kind=Certificate (test-harbor/harborcluster-sample-harbor-harbor-core-tokencert)\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).ProcessFunc.func1\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/controller/resource.go:147\ngithub.com/goharbor/harbor-operator/pkg/graph.(*resourceManager).Run.func1\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/graph/runner.go:42\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_amd64.s:1571\ncannot set status to error: cannot set conditions to error: apply cert-manager.io/v1, Kind=Certificate (test-harbor/harborcluster-sample-harbor-harbor-core-tokencert): apply: admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).HandleError\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/controller/errors.go:61\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Reconcile\n\t/home/runner/work/harbor-operator/harbor-operator/pkg/controller/common.go:157\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_amd64.s:1571"}
```

3、I analyzed the source code and saw that `harbor.Spec.Core.TokenIssuer` style set `omitempty`, but `Certificate.Spec.IssuerRef` is not `omitempty`, so there is a problem here.
