### ISSUE TITLE
Use one unified root ca cert to protect exposed core and notary ingresses

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#95]
When we enable notary (TLS must be enabled), shall we update the following customization files that are located at `config/`?

- `harbor-full/harbor_notary_patch.yaml`
```yaml
apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  notary:
    migrationEnabled: true
  expose:
    notary:
      ingress:
        host: notary.harbor.domain
     tls:  // add tls config and share the same root cert with core?
        certificateRef: sample-public-certificate
```

- `harbor/https.yaml`

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sample-public-certificate
spec:
  isCA: false
  issuerRef:
    name: sample-public-certificate
  secretName: sample-public-certificate
  dnsNames:
  - core.harbor.domain
  - notary.harbor.domain # add notary domain here?
```

**Comment by steven-zou** [comment]
When we enable notary (TLS must be enabled), shall we update the following customization files that are located at `config/`?

- `harbor-full/harbor_notary_patch.yaml`
```yaml
apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  notary:
    migrationEnabled: true
  expose:
    notary:
      ingress:
        host: notary.harbor.domain
     tls:  // add tls config and share the same root cert with core?
        certificateRef: sample-public-certificate
```

- `harbor/https.yaml`

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sample-public-certificate
spec:
  isCA: false
  issuerRef:
    name: sample-public-certificate
  secretName: sample-public-certificate
  dnsNames:
  - core.harbor.domain
  - notary.harbor.domain # add notary domain here?
```
