### ISSUE TITLE
Allow setting up core encryptionKey secret

### ISSUE THREAD

**Issue by vmwiz** [goharbor/harbor-operator#953]
Please allow setting up a secret reference containing the core encryptionKey value to allow running harbor in active-active mode.

At the moment two harbor instances deployed using the same shared database are giving issues with sensitive values stored in the database (e.g. LDAP authentication credentials) due to the fact the core encryptionKey value is randomly generated by the operator.

Pre-provisioning the secret `harbor-harbor-harbor-core-encryptionkey` does not work, the core service refuse to deploy

**Comment by bitsf** [comment]
I remember it's not only to just set this encryptionkey to archive the target.

**Comment by vmwiz** [comment]
You're right, after many headaches to achieve an active-active HA setup with the harbor operator I went for a helm based deployment, I will close this issue.

For reference, here are the helm values I had to share between both instances to create an active-active HA cluster:

```
core:
  secret: 
  xsrfKey: 

database:
  external:
    username:
    password:

harborAdminPassword:

jobservice:
  secret:

persistence:
  imageChartStorage:
    s3:
      accesskey:
      secretkey:

registry:
  credentials: 
    username: harbor_registry_user
    password: 
    htpasswdString: 
  secret: 

secretKey:
```
