### ISSUE TITLE
AWS ALB wrong target group health check for core service

### ISSUE THREAD

**Issue by xoanmi** [goharbor/harbor-operator#967]
### Problem

When exposing the harbor cluster with an **AWS ALB Ingress controller**, the Core's target group is using the default health check:

![image](https://user-images.githubusercontent.com/17291695/193264548-f6695201-122a-42dc-a86f-63bd4786ea34.png)

### How to reproduce it

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harborcluster
spec:
  expose:
    # Expose core services
    core:
      ingress:
        host: harbor.example.com
        controller: default
        annotations:
          alb.ingress.kubernetes.io/backend-protocol: HTTPS
          alb.ingress.kubernetes.io/certificate-arn: foo
          alb.ingress.kubernetes.io/group.name: harbor
          alb.ingress.kubernetes.io/ip-address-type: ipv4
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
          alb.ingress.kubernetes.io/load-balancer-name: harbor
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/ssl-redirect: "443"
          alb.ingress.kubernetes.io/target-type: ip
        ingressClassName: alb
  externalURL: https://harborexample.com
  harborAdminPasswordRef: harbor-admin-password
  version: "2.5.4"
  internalTLS:
    enabled: true
```

#### Option 1

Inject the following annotation on the core's service object to target the right health check path:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ...
    alb.ingress.kubernetes.io/healthcheck-path: /api/v2.0/ping
    ...
```

#### Option 2

At the `harborcluster` crd, allows the definitions of arbitrary annotations at the service level
