### ISSUE TITLE
Feature request - Support custom annotations

### ISSUE THREAD

**Issue by xoanmi** [goharbor/harbor-operator#969]
**Is your feature request related to a problem? Please describe.**
Currently, the operator doesn't support injecting custom annotations.

**Describe the solution you'd like**
```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  # These annotations should be injected into all objects created by the operator
  annotations:
    foo: 'xyz'
spec:
  core:
    # These annotations should be injected only into core components
    annotations:
      bar: 'abc'
```

**Describe the main design/architecture of your solution**
Be able to define generic annotations that will be injected in all objects as well as custom annotations per component (core, registry, trivy, etc).

**Additional context**
We would like to configure **Monitor Prometheus metrics** with dynatrace so we need to annotate the pods who export metrics: exporter, core, jobservice, and registry.

```yaml
annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/path/to-metrics'
    metrics.dynatrace.com/port: '9001'
```
