### ISSUE TITLE
Robot account token is not added to the regcred secret by PSB controller

### ISSUE THREAD

**Issue by vrabbi** [goharbor/harbor-operator#995]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When using the HSC and namespace labels for project and robot auto creation, i expect the dockercofigjson json to include the token for the robot account.
In practice the secret is created and the password field is empty:
```json
{"auths":{"https://harbor.vrabbi.cloud":{"username":"robot$sample-ns-01-bgy0m4+4k8s-6qcbmk","password":"","email":"robot$sample-ns-01-bgy0m4+4k8s-6qcbmk@goharbor.io","auth":"cm9ib3Qkc2FtcGxlLW5zLTAxLWJneTBtNCs0azhzLTZxY2Jtazo="}}}
```

**Steps to reproduce the problem:**
harbor is deployed not via the operator but any one should work the same.
steps to produce:
1. deploy operator from release 1.3.0 deployment yaml
2.  create hsc:
``` yaml
apiVersion: goharbor.io/v1beta1
kind: HarborServerConfiguration
metadata:
  name: vrabbi-harbor
spec:
  default: true ## whether it will be default global hsc
  serverURL: https://harbor.vrabbi.cloud ## https/http is required
  accessCredential:
    namespace: harbor-operator-ns
    accessSecretRef:  harbor-admin-creds
  version: 2.5.3
  insecure: true
```
3. create a nsamespace with the labels:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sample-ns-01
  annotations:
    goharbor.io/harbor: vrabbi-harbor
    goharbor.io/service-account: default
    goharbor.io/project: "*"
  labels:
    harbor-day2-webhook-configuration: enabled
```

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.3.0
- harbor version: 2.5.3
- kubernetes version: 1.23.8
- Any additional relevant versions such as CertManager

**Additional context:**
- **Kubernetes:** TKGm 1.6 cluster on vSphere with TKGm packaged harbor with public letsencrypt cert
